package com.example.yuekao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.yuekao.db.Gouwuche;
import com.example.yuekao.db.Gouwucheche;
import com.example.yuekao.db.liulan;

import com.example.yuekao.db.GouwucheDao;
import com.example.yuekao.db.GouwuchecheDao;
import com.example.yuekao.db.liulanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gouwucheDaoConfig;
    private final DaoConfig gouwuchecheDaoConfig;
    private final DaoConfig liulanDaoConfig;

    private final GouwucheDao gouwucheDao;
    private final GouwuchecheDao gouwuchecheDao;
    private final liulanDao liulanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gouwucheDaoConfig = daoConfigMap.get(GouwucheDao.class).clone();
        gouwucheDaoConfig.initIdentityScope(type);

        gouwuchecheDaoConfig = daoConfigMap.get(GouwuchecheDao.class).clone();
        gouwuchecheDaoConfig.initIdentityScope(type);

        liulanDaoConfig = daoConfigMap.get(liulanDao.class).clone();
        liulanDaoConfig.initIdentityScope(type);

        gouwucheDao = new GouwucheDao(gouwucheDaoConfig, this);
        gouwuchecheDao = new GouwuchecheDao(gouwuchecheDaoConfig, this);
        liulanDao = new liulanDao(liulanDaoConfig, this);

        registerDao(Gouwuche.class, gouwucheDao);
        registerDao(Gouwucheche.class, gouwuchecheDao);
        registerDao(liulan.class, liulanDao);
    }
    
    public void clear() {
        gouwucheDaoConfig.clearIdentityScope();
        gouwuchecheDaoConfig.clearIdentityScope();
        liulanDaoConfig.clearIdentityScope();
    }

    public GouwucheDao getGouwucheDao() {
        return gouwucheDao;
    }

    public GouwuchecheDao getGouwuchecheDao() {
        return gouwuchecheDao;
    }

    public liulanDao getLiulanDao() {
        return liulanDao;
    }

}
